### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'transition')

### ISSUE THREAD

**Issue by cssho** [vscodejp/conference#39]
画面ロード時に以下のエラーが発生
![image](https://user-images.githubusercontent.com/9441609/198690998-3be79c1b-45d2-4913-9333-34744df259e5.png)
`yarn 2023-app:dev` では発生しないがproduction向けにビルドしたもののみで発生している。
この影響でダークモードの切り替え等が動作しなくなる。

**Comment by cssho** [comment]
reactを17にしたら出ない？

**Comment by jiyuujin** [comment]
Nx 15 へ更新すると解決しそうですね

**Comment by cssho** [comment]
https://github.com/vscodejp/conference/pull/78
おそらくこの変更で再発

**Comment by jiyuujin** [comment]
ひとまず戻しました
