### ISSUE TITLE
スタッフ陣のプロフィール

### ISSUE THREAD

**Issue by suzukin** [vscodejp/conference#6]
各自お願いします！

HTMLはここ
https://github.com/vscodejp/conference-website-2021/blob/main/contents/members.ts

画像ファイルのパスはここ、仕様は jiyuujin を参考に
/conference-website-2021/public/icons

**Comment by jiyuujin** [comment]
新たに入られたスタッフさんに、まずアイコンを設定していただければ 🙏

/apps/2023-app/src/contents/staffs.ts

**Comment by jiyuujin** [comment]
新たに入られたスタッフさんに、まずアイコンを設定していただければ 🙏

HTMLはここ
https://github.com/vscodejp/conference/blob/main/apps/2023-app/src/contents/staffs.ts

/apps/2023-app/src/contents/staffs.ts

**Comment by jiyuujin** [comment]
いったん追加し終えた (認識な) ので close します
